desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "SecureMedia", use_legacy_build_api: true) # Build your app - more options available
    pilot(team_name: "com.hanlin")

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end